/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seasbase_video_io_VideoReader */

#ifndef _Included_com_seasbase_video_io_VideoReader
#define _Included_com_seasbase_video_io_VideoReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seasbase_video_io_VideoReader
 * Method:    DiffProc
 * Signature: (Lorg/bytedeco/javacpp/opencv_core/IplImage;IILjava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_seasbase_video_io_VideoReader_DiffProc
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
