/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seasbase_video_io_VideoReader_Info */

#ifndef _Included_com_seasbase_video_io_VideoReader_Info
#define _Included_com_seasbase_video_io_VideoReader_Info
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
