/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seasbase_video_io_VideoReader */

#ifndef _Included_com_seasbase_video_io_VideoReader
#define _Included_com_seasbase_video_io_VideoReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seasbase_video_io_VideoReader
 * Method:    DiffProc
 * Signature: (Lorg/bytedeco/javacpp/opencv_core/IplImage;IILjava/util/List;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_redhadoope_io_obj_VideoReader_DiffProc
  (JNIEnv *, jobject, jobject, jint,jint,jobject);

/*
/*
 * Class:     com_seasbase_video_io_VideoReader
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_redhadoope_io_obj_VideoReader_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
